stages:
  - build
  - build-docker-image
  - push-image-to-docker-hub

build-java-project:
  stage: build
  tags:
      - docker
  script:
  - mvn package

build-docker-image:
  stage: build-docker-image
  tags:
    - docker
  script:
    - docker build -t sfirman87/java-tomcat .
Push Docker Image to DockerHub:
  stage: push-image-to-docker-hub
  tags:
    - docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker push sfirman87/java-tomcat
